export const ADD_CONGRESS_MEMBER = "ADD_CONGRESS_MEMBER";
export const UPDATE_CONGRESS_MEMBER = "UPDATE_CONGRESS_MEMBER";
export const DELETE_CONGRESS_MEMBER = "DELETE_CONGRESS_MEMBER";
export const GET_CONGRESS_MEMBER = "GET_CONGRESS_MEMBER";

export const LOADING = "LOADING";
